In [1]:
import pandas as pd

In [2]:
fight_results = pd.read_csv('../data/processed/fighters.csv')
df = pd.read_csv("../data/processed/cleaned_data.csv")

In [3]:
df = df.drop(columns=['Unnamed: 0'], errors='ignore')

In [4]:
df

,age_A,age_B,height_A,height_B,reach_A,reach_B,stance_A,stance_B,weight_A,weight_B,...,judge1_B,judge2_A,judge2_B,judge3_A,judge3_B,class_A,class_B,rank_A,rank_B,class_diff
0,35.0,27.0,179.0,175.0,178.0,179.0,Orthodox,Orthodox,85.067857,85.067857,...,118.0,115.0,113.0,114.0,114.0,Cruiserweight,Cruiserweight,16,16,0
1,26.0,31.0,173.0,185.0,179.0,185.0,Orthodox,Orthodox,101.736004,101.736004,...,108.0,120.0,108.0,120.0,108.0,Heavyweight,Heavyweight,17,17,0
2,28.0,43.0,176.0,175.0,178.0,179.0,Orthodox,Orthodox,73.556933,73.959501,...,54.0,57.0,54.0,58.0,54.0,Super Middleweight,Super Middleweight,14,14,0
3,25.0,29.0,175.0,174.0,178.0,180.0,Orthodox,Orthodox,70.045370,70.045370,...,48.0,49.0,46.0,48.0,47.0,Middleweight,Middleweight,13,13,0
4,25.0,35.0,175.0,173.0,179.0,170.0,Orthodox,Orthodox,69.239917,69.239917,...,110.0,119.0,109.0,117.0,111.0,Super Welterweight,Super Welterweight,12,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403017,24.0,27.0,184.0,185.0,178.0,196.0,Orthodox,Orthodox,77.893897,77.893897,...,54.0,57.0,54.0,58.0,54.0,Light Heavyweight,Light Heavyweight,15,15,0
403018,26.0,26.0,173.0,173.0,178.0,178.0,Orthodox,Orthodox,75.957415,75.957415,...,54.0,57.0,54.0,58.0,54.0,Super Middleweight,Super Middleweight,14,14,0
403019,26.0,34.0,171.0,170.0,169.0,178.0,Orthodox,Orthodox,71.253439,73.191355,...,9.0,10.0,9.0,10.0,9.0,Middleweight,Super Middleweight,13,14,1
403020,22.0,20.0,173.0,173.0,178.0,178.0,Southpaw,Southpaw,81.222000,81.222000,...,54.0,57.0,54.0,58.0,54.0,Cruiserweight,Cruiserweight,16,16,0
403021,33.0,19.0,173.0,173.0,178.0,178.0,Southpaw,Southpaw,72.847070,72.847070,...,54.0,57.0,54.0,58.0,54.0,Super Middleweight,Super Middleweight,14,14,0

In [5]:
fight_results = fight_results[fight_results['Boxer_A'] != fight_results['Boxer_B']]

In [6]:
fight_results

,Unnamed: 0,Rating_A,Boxer_A,Country_A,Weight_A,Sex,Weight_Class,Rating_B,Boxer_B,Country_B,Weight_B
1,1,1,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,18,"Beterbiev, Artur",RU,79.378665
2,2,1,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,25,"Bivol, Dmitry",RU,79.378665
3,3,1,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,29,"Briedis, Mairis",LV,90.718474
4,4,1,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,48,"Benavidez, David",US,76.203518
5,5,1,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,49,"Berlanga, Edgar",US,76.203518
...,...,...,...,...,...,...,...,...,...,...,...
332615,332615,1469,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1412,"Rose, Brian",GB,72.574779
332616,332616,1469,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1433,"Cash, Quatavious",US,72.574779
332617,332617,1469,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1451,"Matthysse Jr, Walter Ezequiel",AR,72.574779
332618,332618,1469,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1454,"Marcial, Eumir",PH,72.574779
332619,332619,1469,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1466,"Walsh, Nico Ali",US,72.574779

In [7]:
merged_final = pd.concat([fight_results.reset_index(drop=True), 
                          df.reset_index(drop=True)], axis=1)

In [8]:
merged_final = pd.concat([fight_results.reset_index(drop=True), 
                          df.reset_index(drop=True)], axis=1)

In [9]:
merged_final = merged_final[merged_final['Boxer_A'] != merged_final['Boxer_B']]

In [10]:
merged_final

,Unnamed: 0,Rating_A,Boxer_A,Country_A,Weight_A,Sex,Weight_Class,Rating_B,Boxer_B,Country_B,...,judge1_B,judge2_A,judge2_B,judge3_A,judge3_B,class_A,class_B,rank_A,rank_B,class_diff
0,1.0,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,18.0,"Beterbiev, Artur",RU,...,118.0,115.0,113.0,114.0,114.0,Cruiserweight,Cruiserweight,16,16,0
1,2.0,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,25.0,"Bivol, Dmitry",RU,...,108.0,120.0,108.0,120.0,108.0,Heavyweight,Heavyweight,17,17,0
2,3.0,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,29.0,"Briedis, Mairis",LV,...,54.0,57.0,54.0,58.0,54.0,Super Middleweight,Super Middleweight,14,14,0
3,4.0,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,48.0,"Benavidez, David",US,...,48.0,49.0,46.0,48.0,47.0,Middleweight,Middleweight,13,13,0
4,5.0,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,49.0,"Berlanga, Edgar",US,...,110.0,119.0,109.0,117.0,111.0,Super Welterweight,Super Welterweight,12,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,54.0,57.0,54.0,58.0,54.0,Light Heavyweight,Light Heavyweight,15,15,0
403018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,54.0,57.0,54.0,58.0,54.0,Super Middleweight,Super Middleweight,14,14,0
403019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,10.0,9.0,10.0,9.0,Middleweight,Super Middleweight,13,14,1
403020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,54.0,57.0,54.0,58.0,54.0,Cruiserweight,Cruiserweight,16,16,0
403021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,54.0,57.0,54.0,58.0,54.0,Super Middleweight,Super Middleweight,14,14,0

In [11]:
merged_final = merged_final.dropna(subset=['Boxer_A', 'Boxer_B'])

In [12]:
merged_final

,Unnamed: 0,Rating_A,Boxer_A,Country_A,Weight_A,Sex,Weight_Class,Rating_B,Boxer_B,Country_B,...,judge1_B,judge2_A,judge2_B,judge3_A,judge3_B,class_A,class_B,rank_A,rank_B,class_diff
0,1.0,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,18.0,"Beterbiev, Artur",RU,...,118.0,115.0,113.0,114.0,114.0,Cruiserweight,Cruiserweight,16,16,0
1,2.0,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,25.0,"Bivol, Dmitry",RU,...,108.0,120.0,108.0,120.0,108.0,Heavyweight,Heavyweight,17,17,0
2,3.0,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,29.0,"Briedis, Mairis",LV,...,54.0,57.0,54.0,58.0,54.0,Super Middleweight,Super Middleweight,14,14,0
3,4.0,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,48.0,"Benavidez, David",US,...,48.0,49.0,46.0,48.0,47.0,Middleweight,Middleweight,13,13,0
4,5.0,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,49.0,"Berlanga, Edgar",US,...,110.0,119.0,109.0,117.0,111.0,Super Welterweight,Super Welterweight,12,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331147,332615.0,1469.0,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1412.0,"Rose, Brian",GB,...,54.0,57.0,54.0,58.0,54.0,Heavyweight,Heavyweight,17,17,0
331148,332616.0,1469.0,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1433.0,"Cash, Quatavious",US,...,54.0,57.0,54.0,58.0,54.0,Heavyweight,Heavyweight,17,17,0
331149,332617.0,1469.0,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1451.0,"Matthysse Jr, Walter Ezequiel",AR,...,54.0,57.0,54.0,58.0,54.0,Heavyweight,Heavyweight,17,17,0
331150,332618.0,1469.0,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1454.0,"Marcial, Eumir",PH,...,54.0,57.0,54.0,57.5,54.0,Super Welterweight,Middleweight,12,13,1
331151,332619.0,1469.0,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1466.0,"Walsh, Nico Ali",US,...,54.0,57.0,54.0,58.0,54.0,Heavyweight,Heavyweight,17,17,0

In [13]:
merged_final = merged_final.drop(columns=['Unnamed: 0'], errors='ignore')

In [14]:
merged_final

,Rating_A,Boxer_A,Country_A,Weight_A,Sex,Weight_Class,Rating_B,Boxer_B,Country_B,Weight_B,...,judge1_B,judge2_A,judge2_B,judge3_A,judge3_B,class_A,class_B,rank_A,rank_B,class_diff
0,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,18.0,"Beterbiev, Artur",RU,79.378665,...,118.0,115.0,113.0,114.0,114.0,Cruiserweight,Cruiserweight,16,16,0
1,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,25.0,"Bivol, Dmitry",RU,79.378665,...,108.0,120.0,108.0,120.0,108.0,Heavyweight,Heavyweight,17,17,0
2,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,29.0,"Briedis, Mairis",LV,90.718474,...,54.0,57.0,54.0,58.0,54.0,Super Middleweight,Super Middleweight,14,14,0
3,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,48.0,"Benavidez, David",US,76.203518,...,48.0,49.0,46.0,48.0,47.0,Middleweight,Middleweight,13,13,0
4,1.0,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,49.0,"Berlanga, Edgar",US,76.203518,...,110.0,119.0,109.0,117.0,111.0,Super Welterweight,Super Welterweight,12,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331147,1469.0,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1412.0,"Rose, Brian",GB,72.574779,...,54.0,57.0,54.0,58.0,54.0,Heavyweight,Heavyweight,17,17,0
331148,1469.0,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1433.0,"Cash, Quatavious",US,72.574779,...,54.0,57.0,54.0,58.0,54.0,Heavyweight,Heavyweight,17,17,0
331149,1469.0,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1451.0,"Matthysse Jr, Walter Ezequiel",AR,72.574779,...,54.0,57.0,54.0,58.0,54.0,Heavyweight,Heavyweight,17,17,0
331150,1469.0,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1454.0,"Marcial, Eumir",PH,72.574779,...,54.0,57.0,54.0,57.5,54.0,Super Welterweight,Middleweight,12,13,1
331151,1469.0,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1466.0,"Walsh, Nico Ali",US,72.574779,...,54.0,57.0,54.0,58.0,54.0,Heavyweight,Heavyweight,17,17,0

In [15]:
cols = ['won_A', 'won_B', 'lost_A', 'lost_B', 'kos_A']

for col in cols:
    merged_final[col] = merged_final[col].fillna(0).astype(int)

In [16]:
# 1. Columns for Fighter A (end with _A or contain _A)
cols_A = [col for col in merged_final.columns if col.endswith('_A')]

# 2. Columns for Fighter B (end with _B or contain _B)
cols_B = [col for col in merged_final.columns if col.endswith('_B')]

# 3. Important fight result columns (put at end if they exist)
result_cols = [col for col in merged_final.columns if col in ['result', 'won_A', 'won_B']]

# 4. Remaining general columns (not in A, B, or result)
other_cols = [col for col in merged_final.columns if col not in cols_A + cols_B + result_cols]

# Final column order
new_order = cols_A + cols_B + other_cols + result_cols

# Apply rearrangement
merged_final = merged_final[new_order]

# Preview
merged_final.head()

,Rating_A,Boxer_A,Country_A,Weight_A,age_A,height_A,reach_A,stance_A,weight_A,won_A,...,judge3_B,class_B,rank_B,Sex,Weight_Class,decision,class_diff,won_A,won_B,result
0,1.0,"Alvarez, Canelo",MX,76.203518,35.0,179.0,178.0,Orthodox,85.067857,37,...,114.0,Cruiserweight,16,Male,Cruiserweight,KO,0,37,49,draw
1,1.0,"Alvarez, Canelo",MX,76.203518,26.0,173.0,179.0,Orthodox,101.736004,48,...,108.0,Heavyweight,17,Male,Cruiserweight,UD,0,48,50,win_A
2,1.0,"Alvarez, Canelo",MX,76.203518,28.0,176.0,178.0,Orthodox,73.556933,23,...,54.0,Super Middleweight,14,Male,Cruiserweight,KO,0,23,47,win_B
3,1.0,"Alvarez, Canelo",MX,76.203518,25.0,175.0,178.0,Orthodox,70.045370,46,...,47.0,Middleweight,13,Male,Cruiserweight,KO,0,46,31,win_A
4,1.0,"Alvarez, Canelo",MX,76.203518,25.0,175.0,179.0,Orthodox,69.239917,45,...,111.0,Super Welterweight,12,Male,Cruiserweight,UD,0,45,40,win_A

In [17]:
df.dtypes

age_A         float64
age_B         float64
height_A      float64
height_B      float64
reach_A       float64
reach_B       float64
stance_A       object
stance_B       object
weight_A      float64
weight_B      float64
won_A         float64
won_B         float64
lost_A        float64
lost_B        float64
drawn_A         int64
drawn_B         int64
kos_A         float64
kos_B         float64
result         object
decision       object
judge1_A      float64
judge1_B      float64
judge2_A      float64
judge2_B      float64
judge3_A      float64
judge3_B      float64
class_A        object
class_B        object
rank_A          int64
rank_B          int64
class_diff      int64
dtype: object

In [18]:
merged_final.duplicated().sum()

0

In [19]:
merged_final.to_csv('../data/processed/final_processed_data/boxing-match-fighters.csv')