In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/boxer_data.csv")

In [3]:
# from notebooks.clean_boxer_info import

In [4]:
df.head()

,Unnamed: 0,Rating,Boxer,Country,Weight,Ceiling,Action,Promoter,Trainer,Sex
0,0,1,"Alvarez, Canelo",MX,168,5.0,4.13,NaN,"Reynoso, Eddy",Male
1,1,2,"Shields, Claressa",US,154,5.0,4.00,Salita,"Jackson, John David",Female
2,2,3,"McCaskill, Jessica",US,147,5.0,4.00,Matchroom,"Ramos, Rick",Female
3,3,4,"Estrada, Seniesa",US,105,5.0,4.00,Golden Boy,"Campos, Dean",Female
4,4,5,"Serrano, Amanda",PR,126,5.0,5.00,Most Valuable Promotions,"Maldonado, Jordan",Female

In [5]:
df['Sex'].value_counts()

Sex
Male      1397
Female      72
Name: count, dtype: int64

In [6]:
df = df.drop(columns=['Promoter'])
# df = df.drop(columns=[0])
df

,Unnamed: 0,Rating,Boxer,Country,Weight,Ceiling,Action,Trainer,Sex
0,0,1,"Alvarez, Canelo",MX,168,5.0,4.13,"Reynoso, Eddy",Male
1,1,2,"Shields, Claressa",US,154,5.0,4.00,"Jackson, John David",Female
2,2,3,"McCaskill, Jessica",US,147,5.0,4.00,"Ramos, Rick",Female
3,3,4,"Estrada, Seniesa",US,105,5.0,4.00,"Campos, Dean",Female
4,4,5,"Serrano, Amanda",PR,126,5.0,5.00,"Maldonado, Jordan",Female
...,...,...,...,...,...,...,...,...,...
1464,1464,1465,"Chance, Rajon",US,122,NaN,2.00,"Chance, Roger",Male
1465,1465,1466,"Walsh, Nico Ali",US,160,NaN,3.00,"Steward, SugarHill",Male
1466,1466,1467,"Fury, Tommy",GB,200,NaN,3.00,"Fury, John",Male
1467,1467,1468,"Julan, Frederic",FR,175,NaN,3.00,NaN,Male
1468,1468,1469,"Barrionuevo, Cesar",AR,160,NaN,2.00,NaN,Male

In [7]:
# Ceiling will be dropped as this is to do with potential and for the purpose of this experiment it will not be included

df = df.drop(columns=['Ceiling'])
df

,Unnamed: 0,Rating,Boxer,Country,Weight,Action,Trainer,Sex
0,0,1,"Alvarez, Canelo",MX,168,4.13,"Reynoso, Eddy",Male
1,1,2,"Shields, Claressa",US,154,4.00,"Jackson, John David",Female
2,2,3,"McCaskill, Jessica",US,147,4.00,"Ramos, Rick",Female
3,3,4,"Estrada, Seniesa",US,105,4.00,"Campos, Dean",Female
4,4,5,"Serrano, Amanda",PR,126,5.00,"Maldonado, Jordan",Female
...,...,...,...,...,...,...,...,...
1464,1464,1465,"Chance, Rajon",US,122,2.00,"Chance, Roger",Male
1465,1465,1466,"Walsh, Nico Ali",US,160,3.00,"Steward, SugarHill",Male
1466,1466,1467,"Fury, Tommy",GB,200,3.00,"Fury, John",Male
1467,1467,1468,"Julan, Frederic",FR,175,3.00,NaN,Male
1468,1468,1469,"Barrionuevo, Cesar",AR,160,2.00,NaN,Male

In [8]:
df = df.drop(columns=['Action'])
df

,Unnamed: 0,Rating,Boxer,Country,Weight,Trainer,Sex
0,0,1,"Alvarez, Canelo",MX,168,"Reynoso, Eddy",Male
1,1,2,"Shields, Claressa",US,154,"Jackson, John David",Female
2,2,3,"McCaskill, Jessica",US,147,"Ramos, Rick",Female
3,3,4,"Estrada, Seniesa",US,105,"Campos, Dean",Female
4,4,5,"Serrano, Amanda",PR,126,"Maldonado, Jordan",Female
...,...,...,...,...,...,...,...
1464,1464,1465,"Chance, Rajon",US,122,"Chance, Roger",Male
1465,1465,1466,"Walsh, Nico Ali",US,160,"Steward, SugarHill",Male
1466,1466,1467,"Fury, Tommy",GB,200,"Fury, John",Male
1467,1467,1468,"Julan, Frederic",FR,175,NaN,Male
1468,1468,1469,"Barrionuevo, Cesar",AR,160,NaN,Male

In [9]:
df = df.drop(columns=['Trainer'])
df

      Unnamed: 0  Rating               Boxer Country Weight     Sex
0              0       1     Alvarez, Canelo      MX    168    Male
1              1       2   Shields, Claressa      US    154  Female
2              2       3  McCaskill, Jessica      US    147  Female
3              3       4    Estrada, Seniesa      US    105  Female
4              4       5     Serrano, Amanda      PR    126  Female
...          ...     ...                 ...     ...    ...     ...
1464        1464    1465       Chance, Rajon      US    122    Male
1465        1465    1466     Walsh, Nico Ali      US    160    Male
1466        1466    1467         Fury, Tommy      GB    200    Male
1467        1467    1468     Julan, Frederic      FR    175    Male
1468        1468    1469  Barrionuevo, Cesar      AR    160    Male

[1469 rows x 6 columns]

In [10]:
df = df.set_index('Unnamed: 0')

In [11]:
df.index.name = 'Boxer_ID'

In [12]:
df.head(25)

          Rating                    Boxer Country Weight     Sex
Boxer_ID
0              1          Alvarez, Canelo      MX    168    Male
1              2        Shields, Claressa      US    154  Female
2              3       McCaskill, Jessica      US    147  Female
3              4         Estrada, Seniesa      US    105  Female
4              5          Serrano, Amanda      PR    126  Female
5              6       Marshall, Savannah      GB    160  Female
6              7            Taylor, Katie      IE    135  Female
7              8           Mayer, Mikaela      US    130  Female
8              9             Inoue, Naoya      JP    118    Male
9             10              Fury, Tyson      GB    HWT    Male
10            11        Lomachenko, Vasyl      UA    135    Male
11            12       Crawford, Terence       US    147    Male
12            13          Usyk, Oleksandr      UA    HWT    Male
13            14         Spence Jr, Errol      US    147    Male
14            15             Taylor, Josh      GB    140    Male
15            16        Shigeoka, Ginjiro      JP    105    Male
16            17  Estrada, Juan Francisco      MX    115    Male
17            18         Beterbiev, Artur      RU    175    Male
18            19         Ortiz Jr, Vergil      US    147    Male
19            20          Lopez, Teofimo       US    135    Male
20            21             Ennis, Jaron      US    147    Male
21            22            Ramirez, Jose      US    140    Male
22            23             Haney, Devin      US    135    Male
23            24          Gonzalez, Roman      NI    115    Male
24            25            Bivol, Dmitry      RU    175    Male

In [13]:
df.tail()

          Rating               Boxer Country Weight   Sex
Boxer_ID
1464        1465       Chance, Rajon      US    122  Male
1465        1466     Walsh, Nico Ali      US    160  Male
1466        1467         Fury, Tommy      GB    200  Male
1467        1468     Julan, Frederic      FR    175  Male
1468        1469  Barrionuevo, Cesar      AR    160  Male

In [14]:
# theres currently an issue with the weight as the cleaner boxer info shows kg whereas this dataset shows lbs
df['Weight'] = pd.to_numeric(df['Weight'], errors='coerce') * 0.45359237

In [15]:
df.head()

          Rating               Boxer Country     Weight     Sex
Boxer_ID
0              1     Alvarez, Canelo      MX  76.203518    Male
1              2   Shields, Claressa      US  69.853225  Female
2              3  McCaskill, Jessica      US  66.678078  Female
3              4    Estrada, Seniesa      US  47.627199  Female
4              5     Serrano, Amanda      PR  57.152639  Female

In [16]:
def assign_weight_class(weight):
    if weight < 52:
        return 'Flyweight'
    elif weight < 57:
        return 'Featherweight'
    elif weight < 63:
        return 'Lightweight'
    elif weight < 69:
        return 'Welterweight'
    elif weight < 76:
        return 'Middleweight'
    elif weight < 91:
        return 'Cruiserweight'
    else:
        return 'Heavyweight'

df['Weight_Class'] = df['Weight'].apply(assign_weight_class)

In [17]:
# Merge to create valid matchups (same sex & weight class)
merge_df_matchup = df.merge(
    df,
    on=['Sex', 'Weight_Class'],
    suffixes=('_A', '_B')
)

# Remove same boxer matchups
print(merge_df_matchup.columns.tolist())

['Rating_A', 'Boxer_A', 'Country_A', 'Weight_A', 'Sex', 'Weight_Class', 'Rating_B', 'Boxer_B', 'Country_B', 'Weight_B']

In [18]:
df = df.reset_index().rename(columns={'index': 'Boxer_ID'})

In [19]:
print(merge_df_matchup.columns.tolist())

['Rating_A', 'Boxer_A', 'Country_A', 'Weight_A', 'Sex', 'Weight_Class', 'Rating_B', 'Boxer_B', 'Country_B', 'Weight_B']

In [21]:
merge_df_matchup

,Rating_A,Boxer_A,Country_A,Weight_A,Sex,Weight_Class,Rating_B,Boxer_B,Country_B,Weight_B
0,1,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,1,"Alvarez, Canelo",MX,76.203518
1,1,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,18,"Beterbiev, Artur",RU,79.378665
2,1,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,25,"Bivol, Dmitry",RU,79.378665
3,1,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,29,"Briedis, Mairis",LV,90.718474
4,1,"Alvarez, Canelo",MX,76.203518,Male,Cruiserweight,48,"Benavidez, David",US,76.203518
...,...,...,...,...,...,...,...,...,...,...
332616,1469,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1433,"Cash, Quatavious",US,72.574779
332617,1469,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1451,"Matthysse Jr, Walter Ezequiel",AR,72.574779
332618,1469,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1454,"Marcial, Eumir",PH,72.574779
332619,1469,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1466,"Walsh, Nico Ali",US,72.574779
332620,1469,"Barrionuevo, Cesar",AR,72.574779,Male,Middleweight,1469,"Barrionuevo, Cesar",AR,72.574779

In [24]:
merge_df_matchup.to_csv("../data/processed/fighters.csv")